# Generated by Django 5.2 on 2026-03-24 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="telegramotp",
            new_name="accounts_te_ref_id_619f72_idx",
            old_name="accounts_tel_ref_id_xxxxxx_idx",
        ),
        migrations.RenameIndex(
            model_name="telegramotp",
            new_name="accounts_te_telegra_c67392_idx",
            old_name="accounts_tel_telegr_xxxxxx_idx",
        ),
        migrations.RenameIndex(
            model_name="telegramotp",
            new_name="accounts_te_expires_9ae866_idx",
            old_name="accounts_tel_expires_xxxxxx_idx",
        ),
    ]
