INDIAN_STOCKS = [
    ("360ONE.NS",    "360 ONE WAM Ltd.",                        "Financial Services",             "IN"),
    ("ABB.NS",       "ABB India Ltd.",                          "Capital Goods",                  "IN"),
    ("ACC.NS",       "ACC Ltd.",                                "Construction Materials",         "IN"),
    ("APLAPOLLO.NS", "APL Apollo Tubes Ltd.",                   "Capital Goods",                  "IN"),
    ("AUBANK.NS",    "AU Small Finance Bank Ltd.",              "Financial Services",             "IN"),
    ("ADANIENSOL.NS","Adani Energy Solutions Ltd.",             "Power",                          "IN"),
    ("ADANIENT.NS",  "Adani Enterprises Ltd.",                  "Metals & Mining",                "IN"),
    ("ADANIGREEN.NS","Adani Green Energy Ltd.",                 "Power",                          "IN"),
    ("ADANIPORTS.NS","Adani Ports and Special Economic Zone",   "Services",                       "IN"),
    ("ADANIPOWER.NS","Adani Power Ltd.",                        "Power",                          "IN"),
    ("ATGL.NS",      "Adani Total Gas Ltd.",                    "Oil Gas & Consumable Fuels",     "IN"),
    ("ABCAPITAL.NS", "Aditya Birla Capital Ltd.",               "Financial Services",             "IN"),
    ("ALKEM.NS",     "Alkem Laboratories Ltd.",                 "Healthcare",                     "IN"),
    ("AMBUJACEM.NS", "Ambuja Cements Ltd.",                     "Construction Materials",         "IN"),
    ("APOLLOHOSP.NS","Apollo Hospitals Enterprise Ltd.",        "Healthcare",                     "IN"),
    ("ASHOKLEY.NS",  "Ashok Leyland Ltd.",                      "Capital Goods",                  "IN"),
    ("ASIANPAINT.NS","Asian Paints Ltd.",                       "Consumer Durables",              "IN"),
    ("ASTRAL.NS",    "Astral Ltd.",                             "Capital Goods",                  "IN"),
    ("AUROPHARMA.NS","Aurobindo Pharma Ltd.",                   "Healthcare",                     "IN"),
    ("DMART.NS",     "Avenue Supermarts Ltd.",                  "Consumer Services",              "IN"),
    ("AXISBANK.NS",  "Axis Bank Ltd.",                          "Financial Services",             "IN"),
    ("BSE.NS",       "BSE Ltd.",                                "Financial Services",             "IN"),
    ("BAJAJ-AUTO.NS","Bajaj Auto Ltd.",                         "Automobile and Auto Components", "IN"),
    ("BAJFINANCE.NS","Bajaj Finance Ltd.",                      "Financial Services",             "IN"),
    ("BAJAJFINSV.NS","Bajaj Finserv Ltd.",                      "Financial Services",             "IN"),
    ("BAJAJHLDNG.NS","Bajaj Holdings & Investment Ltd.",        "Financial Services",             "IN"),
    ("BAJAJHFL.NS",  "Bajaj Housing Finance Ltd.",              "Financial Services",             "IN"),
    ("BANKBARODA.NS","Bank of Baroda",                          "Financial Services",             "IN"),
    ("BANKINDIA.NS", "Bank of India",                           "Financial Services",             "IN"),
    ("BDL.NS",       "Bharat Dynamics Ltd.",                    "Capital Goods",                  "IN"),
    ("BEL.NS",       "Bharat Electronics Ltd.",                 "Capital Goods",                  "IN"),
    ("BHARATFORG.NS","Bharat Forge Ltd.",                       "Automobile and Auto Components", "IN"),
    ("BHEL.NS",      "Bharat Heavy Electricals Ltd.",           "Capital Goods",                  "IN"),
    ("BPCL.NS",      "Bharat Petroleum Corporation Ltd.",       "Oil Gas & Consumable Fuels",     "IN"),
    ("BHARTIARTL.NS","Bharti Airtel Ltd.",                      "Telecommunication",              "IN"),
    ("BHARTIHEXA.NS","Bharti Hexacom Ltd.",                     "Telecommunication",              "IN"),
    ("BIOCON.NS",    "Biocon Ltd.",                             "Healthcare",                     "IN"),
    ("BLUESTARCO.NS","Blue Star Ltd.",                          "Consumer Durables",              "IN"),
    ("BOSCHLTD.NS",  "Bosch Ltd.",                              "Automobile and Auto Components", "IN"),
    ("BRITANNIA.NS", "Britannia Industries Ltd.",               "Fast Moving Consumer Goods",     "IN"),
    ("CGPOWER.NS",   "CG Power and Industrial Solutions Ltd.",  "Capital Goods",                  "IN"),
    ("CANBK.NS",     "Canara Bank",                             "Financial Services",             "IN"),
    ("CHOLAFIN.NS",  "Cholamandalam Investment and Finance",    "Financial Services",             "IN"),
    ("CIPLA.NS",     "Cipla Ltd.",                              "Healthcare",                     "IN"),
    ("COALINDIA.NS", "Coal India Ltd.",                         "Oil Gas & Consumable Fuels",     "IN"),
    ("COCHINSHIP.NS","Cochin Shipyard Ltd.",                    "Capital Goods",                  "IN"),
    ("COFORGE.NS",   "Coforge Ltd.",                            "Information Technology",         "IN"),
    ("COLPAL.NS",    "Colgate Palmolive (India) Ltd.",          "Fast Moving Consumer Goods",     "IN"),
    ("CONCOR.NS",    "Container Corporation of India Ltd.",     "Services",                       "IN"),
    ("COROMANDEL.NS","Coromandel International Ltd.",           "Chemicals",                      "IN"),
    ("CUMMINSIND.NS","Cummins India Ltd.",                      "Capital Goods",                  "IN"),
    ("DLF.NS",       "DLF Ltd.",                                "Realty",                         "IN"),
    ("DABUR.NS",     "Dabur India Ltd.",                        "Fast Moving Consumer Goods",     "IN"),
    ("DIVISLAB.NS",  "Divi's Laboratories Ltd.",                "Healthcare",                     "IN"),
    ("DIXON.NS",     "Dixon Technologies (India) Ltd.",         "Consumer Durables",              "IN"),
    ("DRREDDY.NS",   "Dr. Reddy's Laboratories Ltd.",           "Healthcare",                     "IN"),
    ("EICHERMOT.NS", "Eicher Motors Ltd.",                      "Automobile and Auto Components", "IN"),
    ("ETERNAL.NS",   "Eternal Ltd.",                            "Consumer Services",              "IN"),
    ("EXIDEIND.NS",  "Exide Industries Ltd.",                   "Automobile and Auto Components", "IN"),
    ("NYKAA.NS",     "FSN E-Commerce Ventures Ltd.",            "Consumer Services",              "IN"),
    ("FEDERALBNK.NS","Federal Bank Ltd.",                       "Financial Services",             "IN"),
    ("FORTIS.NS",    "Fortis Healthcare Ltd.",                  "Healthcare",                     "IN"),
    ("GAIL.NS",      "GAIL (India) Ltd.",                       "Oil Gas & Consumable Fuels",     "IN"),
    ("GMRAIRPORT.NS","GMR Airports Ltd.",                       "Services",                       "IN"),
    ("GLENMARK.NS",  "Glenmark Pharmaceuticals Ltd.",           "Healthcare",                     "IN"),
    ("GODFRYPHLP.NS","Godfrey Phillips India Ltd.",             "Fast Moving Consumer Goods",     "IN"),
    ("GODREJCP.NS",  "Godrej Consumer Products Ltd.",           "Fast Moving Consumer Goods",     "IN"),
    ("GODREJPROP.NS","Godrej Properties Ltd.",                  "Realty",                         "IN"),
    ("GRASIM.NS",    "Grasim Industries Ltd.",                  "Construction Materials",         "IN"),
    ("HCLTECH.NS",   "HCL Technologies Ltd.",                   "Information Technology",         "IN"),
    ("HDFCAMC.NS",   "HDFC Asset Management Company Ltd.",      "Financial Services",             "IN"),
    ("HDFCBANK.NS",  "HDFC Bank Ltd.",                          "Financial Services",             "IN"),
    ("HDFCLIFE.NS",  "HDFC Life Insurance Company Ltd.",        "Financial Services",             "IN"),
    ("HAVELLS.NS",   "Havells India Ltd.",                      "Consumer Durables",              "IN"),
    ("HEROMOTOCO.NS","Hero MotoCorp Ltd.",                      "Automobile and Auto Components", "IN"),
    ("HINDALCO.NS",  "Hindalco Industries Ltd.",                "Metals & Mining",                "IN"),
    ("HAL.NS",       "Hindustan Aeronautics Ltd.",              "Capital Goods",                  "IN"),
    ("HINDPETRO.NS", "Hindustan Petroleum Corporation Ltd.",    "Oil Gas & Consumable Fuels",     "IN"),
    ("HINDUNILVR.NS","Hindustan Unilever Ltd.",                 "Fast Moving Consumer Goods",     "IN"),
    ("HINDZINC.NS",  "Hindustan Zinc Ltd.",                     "Metals & Mining",                "IN"),
    ("POWERINDIA.NS","Hitachi Energy India Ltd.",               "Capital Goods",                  "IN"),
    ("HUDCO.NS",     "Housing & Urban Development Corporation", "Financial Services",             "IN"),
    ("HYUNDAI.NS",   "Hyundai Motor India Ltd.",                "Automobile and Auto Components", "IN"),
    ("ICICIBANK.NS", "ICICI Bank Ltd.",                         "Financial Services",             "IN"),
    ("ICICIGI.NS",   "ICICI Lombard General Insurance",         "Financial Services",             "IN"),
    ("IDFCFIRSTB.NS","IDFC First Bank Ltd.",                    "Financial Services",             "IN"),
    ("IRB.NS",       "IRB Infrastructure Developers Ltd.",      "Construction",                   "IN"),
    ("ITCHOTELS.NS", "ITC Hotels Ltd.",                         "Consumer Services",              "IN"),
    ("ITC.NS",       "ITC Ltd.",                                "Fast Moving Consumer Goods",     "IN"),
    ("INDIANB.NS",   "Indian Bank",                             "Financial Services",             "IN"),
    ("INDHOTEL.NS",  "Indian Hotels Co. Ltd.",                  "Consumer Services",              "IN"),
    ("IOC.NS",       "Indian Oil Corporation Ltd.",             "Oil Gas & Consumable Fuels",     "IN"),
    ("IRCTC.NS",     "Indian Railway Catering And Tourism",     "Consumer Services",              "IN"),
    ("IRFC.NS",      "Indian Railway Finance Corporation Ltd.", "Financial Services",             "IN"),
    ("IREDA.NS",     "Indian Renewable Energy Dev Agency",      "Financial Services",             "IN"),
    ("IGL.NS",       "Indraprastha Gas Ltd.",                   "Oil Gas & Consumable Fuels",     "IN"),
    ("INDUSTOWER.NS","Indus Towers Ltd.",                       "Telecommunication",              "IN"),
    ("INDUSINDBK.NS","IndusInd Bank Ltd.",                      "Financial Services",             "IN"),
    ("NAUKRI.NS",    "Info Edge (India) Ltd.",                  "Consumer Services",              "IN"),
    ("INFY.NS",      "Infosys Ltd.",                            "Information Technology",         "IN"),
    ("INDIGO.NS",    "InterGlobe Aviation Ltd.",                "Services",                       "IN"),
    ("JSWENERGY.NS", "JSW Energy Ltd.",                         "Power",                          "IN"),
    ("JSWSTEEL.NS",  "JSW Steel Ltd.",                          "Metals & Mining",                "IN"),
    ("JINDALSTEL.NS","Jindal Steel Ltd.",                       "Metals & Mining",                "IN"),
    ("JIOFIN.NS",    "Jio Financial Services Ltd.",             "Financial Services",             "IN"),
    ("JUBLFOOD.NS",  "Jubilant Foodworks Ltd.",                 "Consumer Services",              "IN"),
    ("KEI.NS",       "KEI Industries Ltd.",                     "Capital Goods",                  "IN"),
    ("KPITTECH.NS",  "KPIT Technologies Ltd.",                  "Information Technology",         "IN"),
    ("KALYANKJIL.NS","Kalyan Jewellers India Ltd.",             "Consumer Durables",              "IN"),
    ("KOTAKBANK.NS", "Kotak Mahindra Bank Ltd.",                "Financial Services",             "IN"),
    ("LTF.NS",       "L&T Finance Ltd.",                        "Financial Services",             "IN"),
    ("LICHSGFIN.NS", "LIC Housing Finance Ltd.",                "Financial Services",             "IN"),
    ("LTM.NS",       "LTIMindtree Ltd.",                        "Information Technology",         "IN"),
    ("LT.NS",        "Larsen & Toubro Ltd.",                    "Construction",                   "IN"),
    ("LICI.NS",      "Life Insurance Corporation of India",     "Financial Services",             "IN"),
    ("LODHA.NS",     "Lodha Developers Ltd.",                   "Realty",                         "IN"),
    ("LUPIN.NS",     "Lupin Ltd.",                              "Healthcare",                     "IN"),
    ("MRF.NS",       "MRF Ltd.",                                "Automobile and Auto Components", "IN"),
    ("M&MFIN.NS",    "Mahindra & Mahindra Financial Services",  "Financial Services",             "IN"),
    ("M&M.NS",       "Mahindra & Mahindra Ltd.",                "Automobile and Auto Components", "IN"),
    ("MANKIND.NS",   "Mankind Pharma Ltd.",                     "Healthcare",                     "IN"),
    ("MARICO.NS",    "Marico Ltd.",                             "Fast Moving Consumer Goods",     "IN"),
    ("MARUTI.NS",    "Maruti Suzuki India Ltd.",                "Automobile and Auto Components", "IN"),
    ("MFSL.NS",      "Max Financial Services Ltd.",             "Financial Services",             "IN"),
    ("MAXHEALTH.NS", "Max Healthcare Institute Ltd.",           "Healthcare",                     "IN"),
    ("MAZDOCK.NS",   "Mazagoan Dock Shipbuilders Ltd.",         "Capital Goods",                  "IN"),
    ("MOTILALOFS.NS","Motilal Oswal Financial Services Ltd.",   "Financial Services",             "IN"),
    ("MPHASIS.NS",   "MphasiS Ltd.",                            "Information Technology",         "IN"),
    ("MUTHOOTFIN.NS","Muthoot Finance Ltd.",                    "Financial Services",             "IN"),
    ("NHPC.NS",      "NHPC Ltd.",                               "Power",                          "IN"),
    ("NMDC.NS",      "NMDC Ltd.",                               "Metals & Mining",                "IN"),
    ("NTPCGREEN.NS", "NTPC Green Energy Ltd.",                  "Power",                          "IN"),
    ("NTPC.NS",      "NTPC Ltd.",                               "Power",                          "IN"),
    ("NATIONALUM.NS","National Aluminium Co. Ltd.",             "Metals & Mining",                "IN"),
    ("NESTLEIND.NS", "Nestle India Ltd.",                       "Fast Moving Consumer Goods",     "IN"),
    ("OBEROIRLTY.NS","Oberoi Realty Ltd.",                      "Realty",                         "IN"),
    ("ONGC.NS",      "Oil & Natural Gas Corporation Ltd.",      "Oil Gas & Consumable Fuels",     "IN"),
    ("OIL.NS",       "Oil India Ltd.",                          "Oil Gas & Consumable Fuels",     "IN"),
    ("PAYTM.NS",     "One 97 Communications Ltd.",              "Financial Services",             "IN"),
    ("OFSS.NS",      "Oracle Financial Services Software Ltd.", "Information Technology",         "IN"),
    ("POLICYBZR.NS", "PB Fintech Ltd.",                         "Financial Services",             "IN"),
    ("PIIND.NS",     "PI Industries Ltd.",                      "Chemicals",                      "IN"),
    ("PAGEIND.NS",   "Page Industries Ltd.",                    "Textiles",                       "IN"),
    ("PATANJALI.NS", "Patanjali Foods Ltd.",                    "Fast Moving Consumer Goods",     "IN"),
    ("PERSISTENT.NS","Persistent Systems Ltd.",                 "Information Technology",         "IN"),
    ("PHOENIXLTD.NS","Phoenix Mills Ltd.",                      "Realty",                         "IN"),
    ("PIDILITIND.NS","Pidilite Industries Ltd.",                "Chemicals",                      "IN"),
    ("POLYCAB.NS",   "Polycab India Ltd.",                      "Capital Goods",                  "IN"),
    ("PFC.NS",       "Power Finance Corporation Ltd.",          "Financial Services",             "IN"),
    ("POWERGRID.NS", "Power Grid Corporation of India Ltd.",    "Power",                          "IN"),
    ("PREMIERENE.NS","Premier Energies Ltd.",                   "Capital Goods",                  "IN"),
    ("PRESTIGE.NS",  "Prestige Estates Projects Ltd.",          "Realty",                         "IN"),
    ("PNB.NS",       "Punjab National Bank",                    "Financial Services",             "IN"),
    ("RECLTD.NS",    "REC Ltd.",                                "Financial Services",             "IN"),
    ("RVNL.NS",      "Rail Vikas Nigam Ltd.",                   "Construction",                   "IN"),
    ("RELIANCE.NS",  "Reliance Industries Ltd.",                "Oil Gas & Consumable Fuels",     "IN"),
    ("SBICARD.NS",   "SBI Cards and Payment Services Ltd.",     "Financial Services",             "IN"),
    ("SBILIFE.NS",   "SBI Life Insurance Company Ltd.",         "Financial Services",             "IN"),
    ("SRF.NS",       "SRF Ltd.",                                "Chemicals",                      "IN"),
    ("MOTHERSON.NS", "Samvardhana Motherson International",     "Automobile and Auto Components", "IN"),
    ("SHREECEM.NS",  "Shree Cement Ltd.",                       "Construction Materials",         "IN"),
    ("SHRIRAMFIN.NS","Shriram Finance Ltd.",                    "Financial Services",             "IN"),
    ("ENRIN.NS",     "Siemens Energy India Ltd.",               "Capital Goods",                  "IN"),
    ("SIEMENS.NS",   "Siemens Ltd.",                            "Capital Goods",                  "IN"),
    ("SOLARINDS.NS", "Solar Industries India Ltd.",             "Chemicals",                      "IN"),
    ("SONACOMS.NS",  "Sona BLW Precision Forgings Ltd.",        "Automobile and Auto Components", "IN"),
    ("SBIN.NS",      "State Bank of India",                     "Financial Services",             "IN"),
    ("SAIL.NS",      "Steel Authority of India Ltd.",           "Metals & Mining",                "IN"),
    ("SUNPHARMA.NS", "Sun Pharmaceutical Industries Ltd.",      "Healthcare",                     "IN"),
    ("SUPREMEIND.NS","Supreme Industries Ltd.",                 "Capital Goods",                  "IN"),
    ("SUZLON.NS",    "Suzlon Energy Ltd.",                      "Capital Goods",                  "IN"),
    ("SWIGGY.NS",    "Swiggy Ltd.",                             "Consumer Services",              "IN"),
    ("TVSMOTOR.NS",  "TVS Motor Company Ltd.",                  "Automobile and Auto Components", "IN"),
    ("TATACOMM.NS",  "Tata Communications Ltd.",                "Telecommunication",              "IN"),
    ("TCS.NS",       "Tata Consultancy Services Ltd.",          "Information Technology",         "IN"),
    ("TATACONSUM.NS","Tata Consumer Products Ltd.",             "Fast Moving Consumer Goods",     "IN"),
    ("TATAELXSI.NS", "Tata Elxsi Ltd.",                         "Information Technology",         "IN"),
    ("TMPV.NS",      "Tata Motors Passenger Vehicles Ltd.",     "Automobile and Auto Components", "IN"),
    ("TATAPOWER.NS", "Tata Power Co. Ltd.",                     "Power",                          "IN"),
    ("TATASTEEL.NS", "Tata Steel Ltd.",                         "Metals & Mining",                "IN"),
    ("TATATECH.NS",  "Tata Technologies Ltd.",                  "Information Technology",         "IN"),
    ("TECHM.NS",     "Tech Mahindra Ltd.",                      "Information Technology",         "IN"),
    ("TITAN.NS",     "Titan Company Ltd.",                      "Consumer Durables",              "IN"),
    ("TORNTPHARM.NS","Torrent Pharmaceuticals Ltd.",            "Healthcare",                     "IN"),
    ("TORNTPOWER.NS","Torrent Power Ltd.",                      "Power",                          "IN"),
    ("TRENT.NS",     "Trent Ltd.",                              "Consumer Services",              "IN"),
    ("TIINDIA.NS",   "Tube Investments of India Ltd.",          "Automobile and Auto Components", "IN"),
    ("UPL.NS",       "UPL Ltd.",                                "Chemicals",                      "IN"),
    ("ULTRACEMCO.NS","UltraTech Cement Ltd.",                   "Construction Materials",         "IN"),
    ("UNIONBANK.NS", "Union Bank of India",                     "Financial Services",             "IN"),
    ("UNITDSPR.NS",  "United Spirits Ltd.",                     "Fast Moving Consumer Goods",     "IN"),
    ("VBL.NS",       "Varun Beverages Ltd.",                    "Fast Moving Consumer Goods",     "IN"),
    ("VEDL.NS",      "Vedanta Ltd.",                            "Metals & Mining",                "IN"),
    ("VMM.NS",       "Vishal Mega Mart Ltd.",                   "Consumer Services",              "IN"),
    ("IDEA.NS",      "Vodafone Idea Ltd.",                      "Telecommunication",              "IN"),
    ("VOLTAS.NS",    "Voltas Ltd.",                             "Consumer Durables",              "IN"),
    ("WAAREEENER.NS","Waaree Energies Ltd.",                    "Capital Goods",                  "IN"),
    ("WIPRO.NS",     "Wipro Ltd.",                              "Information Technology",         "IN"),
    ("YESBANK.NS",   "Yes Bank Ltd.",                           "Financial Services",             "IN"),
    ("ZYDUSLIFE.NS", "Zydus Lifesciences Ltd.",                 "Healthcare",                     "IN"),
]

US_STOCKS = [
    ("NVDA",  "Nvidia",                       "Technology",             "US"),
    ("AAPL",  "Apple Inc.",                   "Technology",             "US"),
    ("MSFT",  "Microsoft",                    "Technology",             "US"),
    ("AMZN",  "Amazon",                       "Consumer Discretionary", "US"),
    ("GOOGL", "Alphabet Inc. (Class A)",      "Technology",             "US"),
    ("GOOG",  "Alphabet Inc. (Class C)",      "Technology",             "US"),
    ("META",  "Meta Platforms",               "Technology",             "US"),
    ("AVGO",  "Broadcom",                     "Technology",             "US"),
    ("TSLA",  "Tesla Inc.",                   "Consumer Discretionary", "US"),
    ("BRK-B", "Berkshire Hathaway",           "Financial Services",     "US"),
    ("WMT",   "Walmart",                      "Consumer Staples",       "US"),
    ("LLY",   "Lilly (Eli)",                  "Healthcare",             "US"),
    ("JPM",   "JPMorgan Chase",               "Financial Services",     "US"),
    ("XOM",   "ExxonMobil",                   "Energy",                 "US"),
    ("V",     "Visa Inc.",                    "Financial Services",     "US"),
    ("JNJ",   "Johnson & Johnson",            "Healthcare",             "US"),
    ("MU",    "Micron Technology",            "Technology",             "US"),
    ("MA",    "Mastercard",                   "Financial Services",     "US"),
    ("COST",  "Costco",                       "Consumer Staples",       "US"),
    ("ORCL",  "Oracle Corporation",           "Technology",             "US"),
    ("CVX",   "Chevron Corporation",          "Energy",                 "US"),
    ("NFLX",  "Netflix",                      "Communication Services", "US"),
    ("ABBV",  "AbbVie",                       "Healthcare",             "US"),
    ("PLTR",  "Palantir Technologies",        "Technology",             "US"),
    ("BAC",   "Bank of America",              "Financial Services",     "US"),
    ("PG",    "Procter & Gamble",             "Consumer Staples",       "US"),
    ("AMD",   "Advanced Micro Devices",       "Technology",             "US"),
    ("KO",    "Coca-Cola Company",            "Consumer Staples",       "US"),
    ("HD",    "Home Depot",                   "Consumer Discretionary", "US"),
    ("CAT",   "Caterpillar Inc.",             "Industrials",            "US"),
    ("CSCO",  "Cisco",                        "Technology",             "US"),
    ("GE",    "GE Aerospace",                 "Industrials",            "US"),
    ("LRCX",  "Lam Research",                 "Technology",             "US"),
    ("AMAT",  "Applied Materials",            "Technology",             "US"),
    ("MRK",   "Merck & Co.",                  "Healthcare",             "US"),
    ("RTX",   "RTX Corporation",              "Industrials",            "US"),
    ("MS",    "Morgan Stanley",               "Financial Services",     "US"),
    ("PM",    "Philip Morris International",  "Consumer Staples",       "US"),
    ("UNH",   "UnitedHealth Group",           "Healthcare",             "US"),
    ("GS",    "Goldman Sachs",                "Financial Services",     "US"),
    ("WFC",   "Wells Fargo",                  "Financial Services",     "US"),
    ("TMUS",  "T-Mobile US",                  "Communication Services", "US"),
    ("GEV",   "GE Vernova",                   "Industrials",            "US"),
    ("IBM",   "IBM",                          "Technology",             "US"),
    ("LIN",   "Linde plc",                    "Materials",              "US"),
    ("MCD",   "McDonald's",                   "Consumer Discretionary", "US"),
    ("INTC",  "Intel",                        "Technology",             "US"),
    ("VZ",    "Verizon",                      "Communication Services", "US"),
    ("PEP",   "PepsiCo",                      "Consumer Staples",       "US"),
    ("AXP",   "American Express",             "Financial Services",     "US"),
    ("T",     "AT&T",                         "Communication Services", "US"),
    ("KLAC",  "KLA Corporation",              "Technology",             "US"),
    ("C",     "Citigroup",                    "Financial Services",     "US"),
    ("AMGN",  "Amgen",                        "Healthcare",             "US"),
    ("NEE",   "NextEra Energy",               "Utilities",              "US"),
    ("ABT",   "Abbott Laboratories",          "Healthcare",             "US"),
    ("CRM",   "Salesforce",                   "Technology",             "US"),
    ("DIS",   "Walt Disney Company",          "Communication Services", "US"),
    ("TMO",   "Thermo Fisher Scientific",     "Healthcare",             "US"),
    ("TJX",   "TJX Companies",               "Consumer Discretionary", "US"),
    ("TXN",   "Texas Instruments",            "Technology",             "US"),
    ("GILD",  "Gilead Sciences",              "Healthcare",             "US"),
    ("ISRG",  "Intuitive Surgical",           "Healthcare",             "US"),
    ("SCHW",  "Charles Schwab Corporation",   "Financial Services",     "US"),
    ("ANET",  "Arista Networks",              "Technology",             "US"),
    ("APH",   "Amphenol",                     "Technology",             "US"),
    ("COP",   "ConocoPhillips",               "Energy",                 "US"),
    ("PFE",   "Pfizer",                       "Healthcare",             "US"),
    ("BA",    "Boeing",                       "Industrials",            "US"),
    ("UBER",  "Uber",                         "Consumer Discretionary", "US"),
    ("DE",    "Deere & Company",              "Industrials",            "US"),
    ("ADI",   "Analog Devices",               "Technology",             "US"),
    ("APP",   "AppLovin Corporation",         "Technology",             "US"),
    ("BLK",   "BlackRock",                    "Financial Services",     "US"),
    ("LMT",   "Lockheed Martin",              "Industrials",            "US"),
    ("HON",   "Honeywell",                    "Industrials",            "US"),
    ("UNP",   "Union Pacific Corporation",    "Industrials",            "US"),
    ("QCOM",  "Qualcomm",                     "Technology",             "US"),
    ("ETN",   "Eaton Corporation",            "Industrials",            "US"),
    ("BKNG",  "Booking Holdings",             "Consumer Discretionary", "US"),
    ("WELL",  "Welltower",                    "Real Estate",            "US"),
    ("DHR",   "Danaher Corporation",          "Healthcare",             "US"),
    ("PANW",  "Palo Alto Networks",           "Technology",             "US"),
    ("SYK",   "Stryker Corporation",          "Healthcare",             "US"),
    ("SPGI",  "S&P Global",                   "Financial Services",     "US"),
    ("LOW",   "Lowe's",                       "Consumer Discretionary", "US"),
    ("INTU",  "Intuit",                       "Technology",             "US"),
    ("CB",    "Chubb Limited",                "Financial Services",     "US"),
    ("ACN",   "Accenture",                    "Technology",             "US"),
    ("PGR",   "Progressive Corporation",      "Financial Services",     "US"),
    ("PLD",   "Prologis",                     "Real Estate",            "US"),
    ("BMY",   "Bristol Myers Squibb",         "Healthcare",             "US"),
    ("NOW",   "ServiceNow",                   "Technology",             "US"),
    ("VRTX",  "Vertex Pharmaceuticals",       "Healthcare",             "US"),
    ("PH",    "Parker Hannifin",              "Industrials",            "US"),
    ("COF",   "Capital One",                  "Financial Services",     "US"),
    ("MDT",   "Medtronic",                    "Healthcare",             "US"),
    ("HCA",   "HCA Healthcare",               "Healthcare",             "US"),
    ("CME",   "CME Group",                    "Financial Services",     "US"),
    ("MCK",   "McKesson Corporation",         "Healthcare",             "US"),
    ("MO",    "Altria",                       "Consumer Staples",       "US"),
    ("GLW",   "Corning Inc.",                 "Technology",             "US"),
    ("SBUX",  "Starbucks",                    "Consumer Discretionary", "US"),
    ("SNDK",  "Sandisk Corporation",          "Technology",             "US"),
    ("SO",    "Southern Company",             "Utilities",              "US"),
    ("CMCSA", "Comcast",                      "Communication Services", "US"),
    ("NEM",   "Newmont",                      "Materials",              "US"),
    ("CRWD",  "CrowdStrike",                  "Technology",             "US"),
    ("BSX",   "Boston Scientific",            "Healthcare",             "US"),
    ("CEG",   "Constellation Energy",         "Utilities",              "US"),
    ("DELL",  "Dell Technologies",            "Technology",             "US"),
    ("ADBE",  "Adobe Inc.",                   "Technology",             "US"),
    ("NOC",   "Northrop Grumman",             "Industrials",            "US"),
    ("WDC",   "Western Digital",              "Technology",             "US"),
    ("DUK",   "Duke Energy",                  "Utilities",              "US"),
    ("EQIX",  "Equinix",                      "Real Estate",            "US"),
    ("GD",    "General Dynamics",             "Industrials",            "US"),
    ("WM",    "Waste Management",             "Industrials",            "US"),
    ("HWM",   "Howmet Aerospace",             "Industrials",            "US"),
    ("STX",   "Seagate Technology",           "Technology",             "US"),
    ("CVS",   "CVS Health",                   "Healthcare",             "US"),
    ("TT",    "Trane Technologies",           "Industrials",            "US"),
    ("ICE",   "Intercontinental Exchange",    "Financial Services",     "US"),
    ("WMB",   "Williams Companies",           "Energy",                 "US"),
    ("BX",    "Blackstone Inc.",              "Financial Services",     "US"),
    ("MRSH",  "Marsh & McLennan Companies",   "Financial Services",     "US"),
    ("MAR",   "Marriott International",       "Consumer Discretionary", "US"),
    ("FDX",   "FedEx",                        "Industrials",            "US"),
    ("ADP",   "Automatic Data Processing",    "Technology",             "US"),
    ("PWR",   "Quanta Services",              "Industrials",            "US"),
    ("AMT",   "American Tower",               "Real Estate",            "US"),
    ("UPS",   "United Parcel Service",        "Industrials",            "US"),
    ("PNC",   "PNC Financial Services",       "Financial Services",     "US"),
    ("SNPS",  "Synopsys",                     "Technology",             "US"),
    ("KKR",   "KKR",                          "Financial Services",     "US"),
    ("USB",   "U.S. Bancorp",                 "Financial Services",     "US"),
    ("JCI",   "Johnson Controls",             "Industrials",            "US"),
    ("BK",    "BNY Mellon",                   "Financial Services",     "US"),
    ("CDNS",  "Cadence Design Systems",       "Technology",             "US"),
    ("NKE",   "Nike Inc.",                    "Consumer Discretionary", "US"),
    ("REGN",  "Regeneron Pharmaceuticals",    "Healthcare",             "US"),
    ("MCO",   "Moody's Corporation",          "Financial Services",     "US"),
    ("ABNB",  "Airbnb",                       "Consumer Discretionary", "US"),
    ("SHW",   "Sherwin-Williams",             "Materials",              "US"),
    ("MSI",   "Motorola Solutions",           "Technology",             "US"),
    ("FCX",   "Freeport-McMoRan",             "Materials",              "US"),
    ("EOG",   "EOG Resources",                "Energy",                 "US"),
    ("MMM",   "3M",                           "Industrials",            "US"),
    ("ITW",   "Illinois Tool Works",          "Industrials",            "US"),
    ("CMI",   "Cummins",                      "Industrials",            "US"),
    ("ORLY",  "O'Reilly Auto Parts",          "Consumer Discretionary", "US"),
    ("KMI",   "Kinder Morgan",                "Energy",                 "US"),
    ("ECL",   "Ecolab",                       "Materials",              "US"),
    ("MNST",  "Monster Beverage",             "Consumer Staples",       "US"),
    ("MDLZ",  "Mondelez International",       "Consumer Staples",       "US"),
    ("EMR",   "Emerson Electric",             "Industrials",            "US"),
    ("CTAS",  "Cintas",                       "Industrials",            "US"),
    ("VLO",   "Valero Energy",                "Energy",                 "US"),
    ("RCL",   "Royal Caribbean Group",        "Consumer Discretionary", "US"),
    ("CSX",   "CSX Corporation",              "Industrials",            "US"),
    ("PSX",   "Phillips 66",                  "Energy",                 "US"),
    ("SLB",   "Schlumberger",                 "Energy",                 "US"),
    ("AON",   "Aon",                          "Financial Services",     "US"),
    ("CI",    "Cigna",                        "Healthcare",             "US"),
    ("MPC",   "Marathon Petroleum",           "Energy",                 "US"),
    ("ROST",  "Ross Stores",                  "Consumer Discretionary", "US"),
    ("CL",    "Colgate-Palmolive",            "Consumer Staples",       "US"),
    ("DASH",  "DoorDash",                     "Consumer Discretionary", "US"),
    ("WBD",   "Warner Bros. Discovery",       "Communication Services", "US"),
    ("AEP",   "American Electric Power",      "Utilities",              "US"),
    ("RSG",   "Republic Services",            "Industrials",            "US"),
    ("CRH",   "CRH plc",                      "Materials",              "US"),
    ("HLT",   "Hilton Worldwide",             "Consumer Discretionary", "US"),
    ("TDG",   "TransDigm Group",              "Industrials",            "US"),
    ("LHX",   "L3Harris",                     "Industrials",            "US"),
    ("GM",    "General Motors",               "Consumer Discretionary", "US"),
    ("APO",   "Apollo Global Management",     "Financial Services",     "US"),
    ("ELV",   "Elevance Health",              "Healthcare",             "US"),
    ("TRV",   "Travelers Companies",          "Financial Services",     "US"),
    ("HOOD",  "Robinhood Markets Inc.",       "Financial Services",     "US"),
    ("COR",   "Cencora",                      "Healthcare",             "US"),
    ("NSC",   "Norfolk Southern Railway",     "Industrials",            "US"),
    ("APD",   "Air Products",                 "Materials",              "US"),
    ("FTNT",  "Fortinet",                     "Technology",             "US"),
    ("SPG",   "Simon Property Group",         "Real Estate",            "US"),
    ("SRE",   "Sempra",                       "Utilities",              "US"),
    ("OXY",   "Occidental Petroleum",         "Energy",                 "US"),
    ("BKR",   "Baker Hughes",                 "Energy",                 "US"),
    ("DLR",   "Digital Realty",               "Real Estate",            "US"),
    ("PCAR",  "Paccar",                       "Industrials",            "US"),
    ("TEL",   "TE Connectivity",              "Technology",             "US"),
    ("O",     "Realty Income",                "Real Estate",            "US"),
    ("OKE",   "ONEOK",                        "Energy",                 "US"),
    ("AJG",   "Arthur J. Gallagher & Co.",    "Financial Services",     "US"),
    ("AFL",   "Aflac",                        "Financial Services",     "US"),
    ("TFC",   "Truist Financial",             "Financial Services",     "US"),
    ("CIEN",  "Ciena Corporation",            "Technology",             "US"),
    ("AZO",   "AutoZone",                     "Consumer Discretionary", "US"),
    ("FANG",  "Diamondback Energy",           "Energy",                 "US"),
    ("ALL",   "Allstate",                     "Financial Services",     "US"),
]

ALL_STOCKS = INDIAN_STOCKS + US_STOCKS
