# Generated by Django 5.0.6 on 2026-03-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_add_user_to_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='geography',
            field=models.CharField(choices=[('IN', 'India'), ('US', 'US')], default='IN', max_length=5),
        ),
        migrations.AddField(
            model_name='stock',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='ticker',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
