# Generated by Django 5.0.6 on 2026-03-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_stock_geography_stock_is_active_stock_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='geography',
            field=models.CharField(blank=True, choices=[('IN', 'India'), ('US', 'US'), ('ALL', 'All')], default='ALL', max_length=5),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_type',
            field=models.CharField(choices=[('default', 'Default'), ('custom', 'Custom')], default='custom', max_length=20),
        ),
    ]
