# Generated by Django 5.0.6 on 2026-03-23 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_portfoliostock'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('sector', models.CharField(max_length=100)),
                ('geography', models.CharField(choices=[('IN', 'India'), ('US', 'US')], default='IN', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['geography', 'sector', 'ticker'],
            },
        ),
        migrations.RemoveField(
            model_name='portfoliostock',
            name='stock',
        ),
        migrations.AddField(
            model_name='portfoliostock',
            name='stock_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_entries', to='portfolio.stockmaster'),
        ),
    ]
