# Generated by Django 5.0.6 on 2026-03-26 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_stockmaster_remove_portfoliostock_stock_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="QualityStock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ai_rating", models.FloatField()),
                ("buy_signal", models.CharField(choices=[("BUY", "Buy"), ("HOLD", "Hold"), ("SELL", "Sell")], max_length=10)),
                ("report_json", models.JSONField(default=dict)),
                ("graphs_data", models.JSONField(default=dict)),
                ("generated_at", models.DateTimeField(auto_now=True)),
                ("selected_by_user", models.BooleanField(default=False)),
                ("portfolio", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="quality_stocks", to="portfolio.portfolio")),
                ("stock", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="quality_reports", to="portfolio.stock")),
            ],
            options={
                "ordering": ["-generated_at", "stock__symbol"],
            },
        ),
        migrations.AddConstraint(
            model_name="qualitystock",
            constraint=models.UniqueConstraint(fields=("portfolio", "stock"), name="uq_quality_stock_portfolio_stock"),
        ),
    ]
