# Generated by Django 5.0.6 on 2026-03-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BronzeNewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(max_length=64, unique=True)),
                ('title', models.TextField()),
                ('url', models.URLField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('published_at', models.CharField(max_length=100)),
                ('company_tags', models.CharField(blank=True, max_length=500)),
                ('source', models.CharField(default='economic_times', max_length=100)),
                ('source_quality', models.FloatField(default=0.8)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-ingested_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=50, unique=True)),
                ('run_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('stocks_total', models.IntegerField(default=0)),
                ('stocks_success', models.IntegerField(default=0)),
                ('stocks_failed', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BronzeStockPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=30)),
                ('company', models.CharField(max_length=200)),
                ('date', models.DateField(db_index=True)),
                ('open', models.FloatField(null=True)),
                ('high', models.FloatField(null=True)),
                ('low', models.FloatField(null=True)),
                ('close', models.FloatField(null=True)),
                ('volume', models.BigIntegerField(null=True)),
                ('source', models.CharField(default='yfinance', max_length=50)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('fetch_run_id', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['ticker', 'date'], name='pipeline_br_ticker_d941ad_idx')],
            },
        ),
    ]
