# Generated by Django 5.0.6 on 2026-03-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SilverCleanedPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=30)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('geography', models.CharField(blank=True, max_length=5)),
                ('date', models.DateField(db_index=True)),
                ('open', models.FloatField(null=True)),
                ('high', models.FloatField(null=True)),
                ('low', models.FloatField(null=True)),
                ('close', models.FloatField(null=True)),
                ('volume', models.BigIntegerField(null=True)),
                ('daily_return', models.FloatField(null=True)),
                ('log_return', models.FloatField(null=True)),
                ('ma_5', models.FloatField(null=True)),
                ('ma_20', models.FloatField(null=True)),
                ('ma_50', models.FloatField(null=True)),
                ('ma_200', models.FloatField(null=True)),
                ('volatility_20', models.FloatField(null=True)),
                ('rsi_14', models.FloatField(null=True)),
                ('macd', models.FloatField(null=True)),
                ('macd_signal', models.FloatField(null=True)),
                ('macd_hist', models.FloatField(null=True)),
                ('bb_upper', models.FloatField(null=True)),
                ('bb_lower', models.FloatField(null=True)),
                ('bb_width', models.FloatField(null=True)),
                ('price_vs_ma20', models.FloatField(null=True)),
                ('price_vs_ma50', models.FloatField(null=True)),
                ('processed_at', models.DateTimeField(auto_now=True)),
                ('source_run_id', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['ticker', 'date'], name='pipeline_si_ticker_2a25fe_idx')],
                'unique_together': {('ticker', 'date')},
            },
        ),
    ]
