# Generated by Django 5.0.6 on 2026-03-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_silvercleanedprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='BronzeStockFundamentals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=30)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('geography', models.CharField(blank=True, max_length=5)),
                ('trailing_pe', models.FloatField(null=True)),
                ('forward_pe', models.FloatField(null=True)),
                ('price_to_book', models.FloatField(null=True)),
                ('price_to_sales', models.FloatField(null=True)),
                ('enterprise_value', models.FloatField(null=True)),
                ('ev_to_ebitda', models.FloatField(null=True)),
                ('profit_margin', models.FloatField(null=True)),
                ('operating_margin', models.FloatField(null=True)),
                ('gross_margin', models.FloatField(null=True)),
                ('return_on_equity', models.FloatField(null=True)),
                ('return_on_assets', models.FloatField(null=True)),
                ('revenue_growth', models.FloatField(null=True)),
                ('earnings_growth', models.FloatField(null=True)),
                ('eps_trailing', models.FloatField(null=True)),
                ('eps_forward', models.FloatField(null=True)),
                ('market_cap', models.FloatField(null=True)),
                ('total_revenue', models.FloatField(null=True)),
                ('free_cashflow', models.FloatField(null=True)),
                ('debt_to_equity', models.FloatField(null=True)),
                ('current_ratio', models.FloatField(null=True)),
                ('beta', models.FloatField(null=True)),
                ('week52_high', models.FloatField(null=True)),
                ('week52_low', models.FloatField(null=True)),
                ('dividend_yield', models.FloatField(null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='yfinance', max_length=50)),
            ],
            options={
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['ticker'], name='pipeline_br_ticker_2a79ff_idx')],
            },
        ),
    ]
