# Generated by Django 5.0.6 on 2026-03-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_bronzestockfundamentals'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldForecastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=30)),
                ('forecast_date', models.DateField()),
                ('predicted_price', models.FloatField()),
                ('current_price', models.FloatField(null=True)),
                ('expected_change_pct', models.FloatField(null=True)),
                ('direction', models.CharField(blank=True, max_length=20)),
                ('model_type', models.CharField(default='linear_regression', max_length=30)),
                ('confidence_r2', models.FloatField(null=True)),
                ('horizon_days', models.IntegerField(default=1)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-forecast_date'],
                'indexes': [models.Index(fields=['ticker', 'forecast_date'], name='pipeline_go_ticker_dcc5da_idx')],
                'unique_together': {('ticker', 'forecast_date', 'model_type')},
            },
        ),
        migrations.CreateModel(
            name='GoldStockSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=30)),
                ('date', models.DateField(db_index=True)),
                ('signal', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('HOLD', 'Hold'), ('NEUTRAL', 'Neutral')], default='NEUTRAL', max_length=10)),
                ('confidence', models.FloatField(default=0.0)),
                ('rsi_signal', models.CharField(blank=True, max_length=10)),
                ('macd_signal', models.CharField(blank=True, max_length=10)),
                ('ma_signal', models.CharField(blank=True, max_length=10)),
                ('close', models.FloatField(null=True)),
                ('rsi_14', models.FloatField(null=True)),
                ('macd', models.FloatField(null=True)),
                ('macd_signal_line', models.FloatField(null=True)),
                ('ma_50', models.FloatField(null=True)),
                ('price_vs_ma20', models.FloatField(null=True)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['ticker', 'date'], name='pipeline_go_ticker_66699d_idx')],
                'unique_together': {('ticker', 'date')},
            },
        ),
    ]
