# Generated by Django 5.0.6 on 2026-03-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0004_goldforecastresult_goldstocksignal"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoldStockInsight",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ticker", models.CharField(db_index=True, max_length=30)),
                ("date", models.DateField(db_index=True)),
                ("pe_ratio", models.FloatField(default=0.0)),
                ("discount_level", models.CharField(default="UNKNOWN", max_length=50)),
                ("opportunity_score", models.FloatField(default=0.0)),
                ("graph_data", models.JSONField(default=dict)),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [models.Index(fields=["ticker", "date"], name="pipeline_go_ticker_d66c07_idx")],
                "unique_together": {("ticker", "date")},
            },
        ),
    ]
