# Generated by Django 5.0.6 on 2026-03-24 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0005_goldstockinsight'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldSectorSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(db_index=True, max_length=100)),
                ('geography', models.CharField(blank=True, db_index=True, max_length=5)),
                ('date', models.DateField(db_index=True)),
                ('sentiment_score', models.FloatField()),
                ('sentiment_label', models.CharField(max_length=20)),
                ('stock_count', models.IntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'sector'],
            },
        ),
        migrations.CreateModel(
            name='SilverSentimentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=30)),
                ('date', models.DateField(db_index=True)),
                ('sentiment_score', models.FloatField()),
                ('sentiment_label', models.CharField(max_length=20)),
                ('article_count', models.IntegerField(default=0)),
                ('finbert_score', models.FloatField(null=True)),
                ('momentum_score', models.FloatField(null=True)),
                ('technical_score', models.FloatField(null=True)),
                ('model_used', models.CharField(default='finbert+price', max_length=50)),
                ('text_mode', models.CharField(default='both', max_length=10)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.RenameIndex(
            model_name='goldstockinsight',
            new_name='pipeline_go_ticker_fd10b0_idx',
            old_name='pipeline_go_ticker_d66c07_idx',
        ),
        migrations.AddIndex(
            model_name='goldsectorsentiment',
            index=models.Index(fields=['sector', 'geography', 'date'], name='pipeline_go_sector_6406a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='goldsectorsentiment',
            unique_together={('sector', 'geography', 'date')},
        ),
        migrations.AddIndex(
            model_name='silversentimentscore',
            index=models.Index(fields=['ticker', 'date'], name='pipeline_si_ticker_a97fc3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='silversentimentscore',
            unique_together={('ticker', 'date')},
        ),
    ]
