# Generated by Django 5.2.11 on 2026-03-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0006_goldsectorsentiment_silversentimentscore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bronzestockprice',
            name='candle_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='bronzestockprice',
            index=models.Index(fields=['ticker', 'candle_at'], name='pipeline_br_ticker_faad15_idx'),
        ),
        migrations.AddConstraint(
            model_name='bronzestockprice',
            constraint=models.UniqueConstraint(fields=('ticker', 'candle_at'), name='uq_bronze_ticker_candle_at'),
        ),
    ]
